spring:
  application:
    name: viswambara-converter

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

integration:
  routing: []
  providers: {}
  mappings: {}
